[[nav]]
name = "About"
url = "about/"
weight = 2

[[nav]]
name = "Services"
url = "service/"
weight = 3

[[nav]]
name = "Contact"
url = "contact/"
weight = 4

[[service]]
name = "Automation"
url = "service/"
weight = 1

[[service]]
name = "Hardware integration"
url = "service/"
weight = 2

[[service]]
name = "AI implementation"
url = "service/"
weight = 3

[[service]]
name = "Engineering prototypes"
url = "service/"
weight = 4

[[quicklink]]
name = "About"
url = "about/"
weight = 1

[[quicklink]]
name = "Services"
url = "service/"
weight = 2

[[quicklink]]
name = "Contact"
url = "contact/"
weight = 3
